apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp-app
  template:
    metadata:
      labels:
        app: tp-app
    spec:
      containers:
        - name: tp-app
          image: khadijabenayed/tp-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql-service:3306/tpdb
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: password
      imagePullSecrets:
        - name: dockerhub-secret

